# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_gaussian', [dirname(__file__)])
        except ImportError:
            import _gaussian
            return _gaussian
        if fp is not None:
            try:
                _mod = imp.load_module('_gaussian', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _gaussian = swig_import_helper()
    del swig_import_helper
else:
    import _gaussian
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def gsl_cdf_ugaussian_P(*args):
  return _gaussian.gsl_cdf_ugaussian_P(*args)
gsl_cdf_ugaussian_P = _gaussian.gsl_cdf_ugaussian_P

def gsl_cdf_ugaussian_Q(*args):
  return _gaussian.gsl_cdf_ugaussian_Q(*args)
gsl_cdf_ugaussian_Q = _gaussian.gsl_cdf_ugaussian_Q

def gsl_cdf_gaussian_P(*args):
  return _gaussian.gsl_cdf_gaussian_P(*args)
gsl_cdf_gaussian_P = _gaussian.gsl_cdf_gaussian_P

def gsl_cdf_gaussian_Q(*args):
  return _gaussian.gsl_cdf_gaussian_Q(*args)
gsl_cdf_gaussian_Q = _gaussian.gsl_cdf_gaussian_Q

def gsl_cdf_ugaussian_Pinv(*args):
  return _gaussian.gsl_cdf_ugaussian_Pinv(*args)
gsl_cdf_ugaussian_Pinv = _gaussian.gsl_cdf_ugaussian_Pinv

def gsl_cdf_ugaussian_Qinv(*args):
  return _gaussian.gsl_cdf_ugaussian_Qinv(*args)
gsl_cdf_ugaussian_Qinv = _gaussian.gsl_cdf_ugaussian_Qinv

def gsl_cdf_gaussian_Pinv(*args):
  return _gaussian.gsl_cdf_gaussian_Pinv(*args)
gsl_cdf_gaussian_Pinv = _gaussian.gsl_cdf_gaussian_Pinv

def gsl_cdf_gaussian_Qinv(*args):
  return _gaussian.gsl_cdf_gaussian_Qinv(*args)
gsl_cdf_gaussian_Qinv = _gaussian.gsl_cdf_gaussian_Qinv
# This file is compatible with both classic and new-style classes.


